apiVersion: v1
kind: Service
metadata:
  labels:
    name: <NAME>
  name: <NAME>
  namespace: default
spec:
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: <NAME>
  type: LoadBalancer
